sent1 = input("Hello, user, please enter a sentence: ").upper()
print(sent1)
para = input("Next, write out a paragraph and we'll tell you how many words are in it: ")
wrdcnt = len(para.split())
print("The number of words are: " + str(wrdcnt))
string = input("Please enter a string: ")
digit = string.isdigit()
print(digit)
string1 = input("Please enter a string: ")
replace = string1.replace("a", "o")
print(replace)
full_name = input("Hello user, please enter your full name: ")
names = full_name.split()
initials = ''.join(name[0].upper() for name in names)
print("Your initials are", initials)
length = input("Please enter a string: ")
amount = len(length)
print("The length of your string is", amount)
print(f"The length of your string is {amount}")